# Note: supported platforms: macOS, Linux and Windows
# Please make sure that's working on all supported platforms
version: "3.9"

services:
  postgres:
    image: postgres:12.8-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./../.docker/statistics/postgresql/data:/var/lib/postgresql/data:z
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/code:z
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
